name: Auto Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ec2-user@${{ secrets.SERVER_IP }} << 'EOF'
            set -e

            echo "ðŸš€ Deploy started"
            cd /var/www/nextgenstep

            sudo chown -R ec2-user:ec2-user .

            git reset --hard
            git clean -fd
            git pull origin main

            /usr/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

            php artisan migrate --force
            php artisan optimize

            sudo systemctl restart php-fpm
            sudo systemctl restart nginx

            echo "âœ… Deploy finished successfully"
          EOF
